### ISSUE TITLE
Have no idea why GLModelView only displays half of the model

### ISSUE THREAD

**Issue by rivertea** [nicklockwood/GLView#29]
Used the `GLModel` to load the .obj with texture, but GLModelView only displays half of the `GLModel`

![](http://i.imgur.com/IR2WSab.png?1)

I added `UIPanGesturerecognizer` to rotate the model, I don't think it's the reason.

Please help to solve.
Cheers

**Comment by elsurudo** [comment]
Having the same issue. Basically there seems to be a threshold, and anything "behind" it is not displayed. In my case, if I rotate the model, I can see different parts of it...

**Comment by elsurudo** [comment]
Have you had any luck with solving this?

**Comment by nicklockwood** [comment]
With all 3D engines, it's impossible to display content that is behind the camera (because it would result in a divide-by-zero in the 3D math).

The reason your object is being clipped if that part of it is behind the camera, because the model itself is positioned too close to the camera. If you translate it along the z axis to move it further away, you will be able to see all of it.

To translate along the z-axis, apply a `CATransform3DTranslate(...)` to the `transform` property.

**Comment by elsurudo** [comment]
Yeah, I knew this and was already doing the translation. My problem turned out to be that I added a rotation before the translation, so the translation translated the model right out of the viewport! Thanks to your comment here though, I took a closer look and solved the issue. Thanks!

**Comment by rivertea** [comment]
Thanks for your answer. It works pretty well now.
